### PR TITLE
fix: typos in voc4cat_template_043.xlsx

### PR DESCRIPTION
**Pull request by markdoerr**
The voc4cat_template_043.xlsx contained a lot of typos (I am not very good at finding typos, but these were quite obvious ;)
Many of them are now, hopefully fixed in a new template version v044.

I would also suggest to keep the format of the **dates** consistent in the template and recommend the **ISO 8601 format YYYY-MM-DD**

### CODE REVIEW

**Comment by dalito** [comment]
Excel stores the date internally as date but shows it according the the locale settings of the user. We would loose this localisation "feature" if we enforce an iso-date in all date fields. I would nevertheless also prefer iso-date if the format can be set reliably from openpyxl. I have never tried to do that.

FYI: The template version number will stay at 043. It will be only incremented if the structure changes.

**Comment by markdoerr** [comment]
that's a good point, @dalito,
with the default localised date settings of Excel.
Let's see, what can be done through openpyxl....

**Comment by markdoerr** [comment]
regarding the template version: I suspected a hidden semver scheme 043 = 0.4.3.
That's why I incremented the "patch" part ;) 
Shall I rename it - or do you first want to compare the two versions with the Excel internal overlay function ? (if it exists)

**Comment by dalito** [comment]
I already compared the files. Obviously, we forgot to run the spell checker on the help sheet. 

Which tool did you use to create the file? Your file expresses the background color of the cells differently. I would therefore replace it with a new file from MS Office if you don't mind. FYI: An online-diff tool is at https://www.diffchecker.com/excel-compare/ and some MS Office versions also include a tool called [Spreadsheet Compare](https://support.microsoft.com/en-au/office/compare-two-versions-of-a-workbook-by-using-spreadsheet-compare-0e1627fd-ce14-4c33-9ab1-8ea82c6a5a7e)).

**Comment by markdoerr** [comment]
I do not mind, @dalito :) 

I used a recent version of LibreOffice to edit the template. 

Thanks also for the Excel diff tool hints - might be interesting in the future....

**Pull request closed without merging**
